import type { AgentPreset } from './types/agent';
import type { ThemeConfig } from './types/theme';
import type { ShellInfo, ShellType } from './types/terminal';
import type { LayoutPreset } from './types/layout';

export const APP_NAME = 'Agenteck';
export const APP_VERSION = '1.0.0';

// Tile snapping configuration
export const DEFAULT_SNAP_ENABLED = true;
export const DEFAULT_SNAP_INCREMENT = 5; // 5% grid

// Safe check for process.platform (not available in renderer)
export const DEFAULT_SHELL: ShellType =
  typeof process !== 'undefined' && process.platform === 'win32' ? 'powershell' : 'bash';

export const SHELL_CONFIGS: Record<string, Partial<ShellInfo>> = {
  powershell: {
    id: 'powershell',
    name: 'PowerShell',
    path: 'powershell.exe',
    args: ['-NoLogo'],
  },
  cmd: {
    id: 'cmd',
    name: 'Command Prompt',
    path: 'cmd.exe',
  },
  bash: {
    id: 'bash',
    name: 'Bash',
    path: '/bin/bash',
    args: ['--login'],
  },
  zsh: {
    id: 'zsh',
    name: 'Zsh',
    path: '/bin/zsh',
    args: ['--login'],
  },
  wsl: {
    id: 'wsl',
    name: 'WSL',
    path: 'wsl.exe',
  },
};

// Available agent presets that users can add to their workspace
export const AVAILABLE_AGENTS: AgentPreset[] = [
  {
    id: 'claude',
    name: 'Claude',
    command: 'claude',
    args: [],
    description: "Anthropic's AI coding assistant",
    website: 'https://claude.ai',
    isBuiltIn: true,
  },
  {
    id: 'gemini',
    name: 'Gemini',
    command: 'gemini',
    args: [],
    description: "Google's AI assistant CLI",
    website: 'https://gemini.google.com',
    isBuiltIn: true,
  },
  {
    id: 'codex',
    name: 'Codex',
    command: 'codex',
    args: [],
    description: "OpenAI's coding assistant",
    website: 'https://openai.com',
    isBuiltIn: true,
  },
  {
    id: 'qwen',
    name: 'Qwen',
    command: 'qwen',
    args: [],
    description: "Alibaba's AI coding assistant",
    website: 'https://qwen.ai',
    isBuiltIn: true,
  },
  {
    id: 'opencode',
    name: 'OpenCode',
    command: 'opencode',
    args: [],
    description: 'Open-source AI code assistant',
    website: 'https://github.com/opencode-ai/opencode',
    isBuiltIn: true,
  },
  {
    id: 'copilot',
    name: 'GitHub Copilot',
    command: 'copilot',
    args: [],
    description: "GitHub's AI-powered coding assistant CLI",
    website: 'https://github.com/features/copilot',
    isBuiltIn: true,
  },
];

export const DEFAULT_TERMINAL_THEME: ThemeConfig = {
  id: 'default-dark',
  name: 'Default Dark',
  isBuiltIn: true,
  colors: {
    background: '#1e1e2e',
    foreground: '#cdd6f4',
    cursor: '#f5e0dc',
    cursorAccent: '#1e1e2e',
    selection: '#45475a',
    selectionForeground: '#cdd6f4',
    black: '#45475a',
    red: '#f38ba8',
    green: '#a6e3a1',
    yellow: '#f9e2af',
    blue: '#89b4fa',
    magenta: '#f5c2e7',
    cyan: '#94e2d5',
    white: '#bac2de',
    brightBlack: '#585b70',
    brightRed: '#f38ba8',
    brightGreen: '#a6e3a1',
    brightYellow: '#f9e2af',
    brightBlue: '#89b4fa',
    brightMagenta: '#f5c2e7',
    brightCyan: '#94e2d5',
    brightWhite: '#a6adc8',
  },
  font: {
    family: '"Cascadia Code", "JetBrains Mono", "Fira Code", Consolas, monospace',
    size: 14,
    lineHeight: 1.2,
  },
  opacity: 1,
};

export const BUILT_IN_THEMES: ThemeConfig[] = [
  DEFAULT_TERMINAL_THEME,
  {
    id: 'dracula',
    name: 'Dracula',
    isBuiltIn: true,
    colors: {
      background: '#282a36',
      foreground: '#f8f8f2',
      cursor: '#f8f8f2',
      selection: '#44475a',
      black: '#21222c',
      red: '#ff5555',
      green: '#50fa7b',
      yellow: '#f1fa8c',
      blue: '#bd93f9',
      magenta: '#ff79c6',
      cyan: '#8be9fd',
      white: '#f8f8f2',
      brightBlack: '#6272a4',
      brightRed: '#ff6e6e',
      brightGreen: '#69ff94',
      brightYellow: '#ffffa5',
      brightBlue: '#d6acff',
      brightMagenta: '#ff92df',
      brightCyan: '#a4ffff',
      brightWhite: '#ffffff',
    },
    font: {
      family: '"Cascadia Code", "JetBrains Mono", "Fira Code", Consolas, monospace',
      size: 14,
      lineHeight: 1.2,
    },
    opacity: 1,
  },
  {
    id: 'nord',
    name: 'Nord',
    isBuiltIn: true,
    colors: {
      background: '#2e3440',
      foreground: '#d8dee9',
      cursor: '#d8dee9',
      selection: '#434c5e',
      black: '#3b4252',
      red: '#bf616a',
      green: '#a3be8c',
      yellow: '#ebcb8b',
      blue: '#81a1c1',
      magenta: '#b48ead',
      cyan: '#88c0d0',
      white: '#e5e9f0',
      brightBlack: '#4c566a',
      brightRed: '#bf616a',
      brightGreen: '#a3be8c',
      brightYellow: '#ebcb8b',
      brightBlue: '#81a1c1',
      brightMagenta: '#b48ead',
      brightCyan: '#8fbcbb',
      brightWhite: '#eceff4',
    },
    font: {
      family: '"Cascadia Code", "JetBrains Mono", "Fira Code", Consolas, monospace',
      size: 14,
      lineHeight: 1.2,
    },
    opacity: 1,
  },
  {
    id: 'monokai',
    name: 'Monokai',
    isBuiltIn: true,
    colors: {
      background: '#272822',
      foreground: '#f8f8f2',
      cursor: '#f8f8f2',
      selection: '#49483e',
      black: '#272822',
      red: '#f92672',
      green: '#a6e22e',
      yellow: '#f4bf75',
      blue: '#66d9ef',
      magenta: '#ae81ff',
      cyan: '#a1efe4',
      white: '#f8f8f2',
      brightBlack: '#75715e',
      brightRed: '#f92672',
      brightGreen: '#a6e22e',
      brightYellow: '#f4bf75',
      brightBlue: '#66d9ef',
      brightMagenta: '#ae81ff',
      brightCyan: '#a1efe4',
      brightWhite: '#f9f8f5',
    },
    font: {
      family: '"Cascadia Code", "JetBrains Mono", "Fira Code", Consolas, monospace',
      size: 14,
      lineHeight: 1.2,
    },
    opacity: 1,
  },
  {
    id: 'tokyo-night',
    name: 'Tokyo Night',
    isBuiltIn: true,
    colors: {
      background: '#1a1b26',
      foreground: '#c0caf5',
      cursor: '#c0caf5',
      selection: '#33467c',
      black: '#15161e',
      red: '#f7768e',
      green: '#9ece6a',
      yellow: '#e0af68',
      blue: '#7aa2f7',
      magenta: '#bb9af7',
      cyan: '#7dcfff',
      white: '#a9b1d6',
      brightBlack: '#414868',
      brightRed: '#f7768e',
      brightGreen: '#9ece6a',
      brightYellow: '#e0af68',
      brightBlue: '#7aa2f7',
      brightMagenta: '#bb9af7',
      brightCyan: '#7dcfff',
      brightWhite: '#c0caf5',
    },
    font: {
      family: '"Cascadia Code", "JetBrains Mono", "Fira Code", Consolas, monospace',
      size: 14,
      lineHeight: 1.2,
    },
    opacity: 1,
  },
  {
    id: 'one-dark-pro',
    name: 'One Dark Pro',
    isBuiltIn: true,
    colors: {
      background: '#282c34',
      foreground: '#abb2bf',
      cursor: '#528bff',
      selection: '#3e4451',
      black: '#282c34',
      red: '#e06c75',
      green: '#98c379',
      yellow: '#e5c07b',
      blue: '#61afef',
      magenta: '#c678dd',
      cyan: '#56b6c2',
      white: '#abb2bf',
      brightBlack: '#5c6370',
      brightRed: '#e06c75',
      brightGreen: '#98c379',
      brightYellow: '#e5c07b',
      brightBlue: '#61afef',
      brightMagenta: '#c678dd',
      brightCyan: '#56b6c2',
      brightWhite: '#ffffff',
    },
    font: {
      family: '"Cascadia Code", "JetBrains Mono", "Fira Code", Consolas, monospace',
      size: 14,
      lineHeight: 1.2,
    },
    opacity: 1,
  },
  {
    id: 'solarized-dark',
    name: 'Solarized Dark',
    isBuiltIn: true,
    colors: {
      background: '#002b36',
      foreground: '#839496',
      cursor: '#839496',
      selection: '#073642',
      black: '#073642',
      red: '#dc322f',
      green: '#859900',
      yellow: '#b58900',
      blue: '#268bd2',
      magenta: '#d33682',
      cyan: '#2aa198',
      white: '#eee8d5',
      brightBlack: '#586e75',
      brightRed: '#cb4b16',
      brightGreen: '#586e75',
      brightYellow: '#657b83',
      brightBlue: '#839496',
      brightMagenta: '#6c71c4',
      brightCyan: '#93a1a1',
      brightWhite: '#fdf6e3',
    },
    font: {
      family: '"Cascadia Code", "JetBrains Mono", "Fira Code", Consolas, monospace',
      size: 14,
      lineHeight: 1.2,
    },
    opacity: 1,
  },
  {
    id: 'solarized-light',
    name: 'Solarized Light',
    isBuiltIn: true,
    colors: {
      background: '#fdf6e3',
      foreground: '#657b83',
      cursor: '#657b83',
      selection: '#eee8d5',
      black: '#073642',
      red: '#dc322f',
      green: '#859900',
      yellow: '#b58900',
      blue: '#268bd2',
      magenta: '#d33682',
      cyan: '#2aa198',
      white: '#eee8d5',
      brightBlack: '#002b36',
      brightRed: '#cb4b16',
      brightGreen: '#586e75',
      brightYellow: '#657b83',
      brightBlue: '#839496',
      brightMagenta: '#6c71c4',
      brightCyan: '#93a1a1',
      brightWhite: '#fdf6e3',
    },
    font: {
      family: '"Cascadia Code", "JetBrains Mono", "Fira Code", Consolas, monospace',
      size: 14,
      lineHeight: 1.2,
    },
    opacity: 1,
  },
  {
    id: 'github-dark',
    name: 'GitHub Dark',
    isBuiltIn: true,
    colors: {
      background: '#0d1117',
      foreground: '#c9d1d9',
      cursor: '#58a6ff',
      selection: '#264f78',
      black: '#484f58',
      red: '#ff7b72',
      green: '#3fb950',
      yellow: '#d29922',
      blue: '#58a6ff',
      magenta: '#bc8cff',
      cyan: '#39c5cf',
      white: '#b1bac4',
      brightBlack: '#6e7681',
      brightRed: '#ffa198',
      brightGreen: '#56d364',
      brightYellow: '#e3b341',
      brightBlue: '#79c0ff',
      brightMagenta: '#d2a8ff',
      brightCyan: '#56d4dd',
      brightWhite: '#f0f6fc',
    },
    font: {
      family: '"Cascadia Code", "JetBrains Mono", "Fira Code", Consolas, monospace',
      size: 14,
      lineHeight: 1.2,
    },
    opacity: 1,
  },
  {
    id: 'github-light',
    name: 'GitHub Light',
    isBuiltIn: true,
    colors: {
      background: '#ffffff',
      foreground: '#24292f',
      cursor: '#0969da',
      selection: '#add6ff',
      black: '#24292f',
      red: '#cf222e',
      green: '#116329',
      yellow: '#9a6700',
      blue: '#0969da',
      magenta: '#8250df',
      cyan: '#1b7c83',
      white: '#6e7781',
      brightBlack: '#57606a',
      brightRed: '#a40e26',
      brightGreen: '#1a7f37',
      brightYellow: '#bf8700',
      brightBlue: '#218bff',
      brightMagenta: '#a475f9',
      brightCyan: '#3192aa',
      brightWhite: '#8c959f',
    },
    font: {
      family: '"Cascadia Code", "JetBrains Mono", "Fira Code", Consolas, monospace',
      size: 14,
      lineHeight: 1.2,
    },
    opacity: 1,
  },
  {
    id: 'gruvbox-dark',
    name: 'Gruvbox Dark',
    isBuiltIn: true,
    colors: {
      background: '#282828',
      foreground: '#ebdbb2',
      cursor: '#ebdbb2',
      selection: '#504945',
      black: '#282828',
      red: '#cc241d',
      green: '#98971a',
      yellow: '#d79921',
      blue: '#458588',
      magenta: '#b16286',
      cyan: '#689d6a',
      white: '#a89984',
      brightBlack: '#928374',
      brightRed: '#fb4934',
      brightGreen: '#b8bb26',
      brightYellow: '#fabd2f',
      brightBlue: '#83a598',
      brightMagenta: '#d3869b',
      brightCyan: '#8ec07c',
      brightWhite: '#ebdbb2',
    },
    font: {
      family: '"Cascadia Code", "JetBrains Mono", "Fira Code", Consolas, monospace',
      size: 14,
      lineHeight: 1.2,
    },
    opacity: 1,
  },
  {
    id: 'material-palenight',
    name: 'Material Palenight',
    isBuiltIn: true,
    colors: {
      background: '#292d3e',
      foreground: '#a6accd',
      cursor: '#ffcc00',
      selection: '#434758',
      black: '#292d3e',
      red: '#f07178',
      green: '#c3e88d',
      yellow: '#ffcb6b',
      blue: '#82aaff',
      magenta: '#c792ea',
      cyan: '#89ddff',
      white: '#d0d0d0',
      brightBlack: '#434758',
      brightRed: '#ff8b92',
      brightGreen: '#ddffa7',
      brightYellow: '#ffe585',
      brightBlue: '#9cc4ff',
      brightMagenta: '#e1acff',
      brightCyan: '#a3f7ff',
      brightWhite: '#ffffff',
    },
    font: {
      family: '"Cascadia Code", "JetBrains Mono", "Fira Code", Consolas, monospace',
      size: 14,
      lineHeight: 1.2,
    },
    opacity: 1,
  },
  {
    id: 'catppuccin-latte',
    name: 'Catppuccin Latte',
    isBuiltIn: true,
    colors: {
      background: '#eff1f5',
      foreground: '#4c4f69',
      cursor: '#dc8a78',
      selection: '#acb0be',
      black: '#5c5f77',
      red: '#d20f39',
      green: '#40a02b',
      yellow: '#df8e1d',
      blue: '#1e66f5',
      magenta: '#ea76cb',
      cyan: '#179299',
      white: '#acb0be',
      brightBlack: '#6c6f85',
      brightRed: '#d20f39',
      brightGreen: '#40a02b',
      brightYellow: '#df8e1d',
      brightBlue: '#1e66f5',
      brightMagenta: '#ea76cb',
      brightCyan: '#179299',
      brightWhite: '#bcc0cc',
    },
    font: {
      family: '"Cascadia Code", "JetBrains Mono", "Fira Code", Consolas, monospace',
      size: 14,
      lineHeight: 1.2,
    },
    opacity: 1,
  },
  {
    id: 'catppuccin-frappe',
    name: 'Catppuccin Frappe',
    isBuiltIn: true,
    colors: {
      background: '#303446',
      foreground: '#c6d0f5',
      cursor: '#f2d5cf',
      selection: '#51576d',
      black: '#51576d',
      red: '#e78284',
      green: '#a6d189',
      yellow: '#e5c890',
      blue: '#8caaee',
      magenta: '#f4b8e4',
      cyan: '#81c8be',
      white: '#b5bfe2',
      brightBlack: '#626880',
      brightRed: '#e78284',
      brightGreen: '#a6d189',
      brightYellow: '#e5c890',
      brightBlue: '#8caaee',
      brightMagenta: '#f4b8e4',
      brightCyan: '#81c8be',
      brightWhite: '#a5adce',
    },
    font: {
      family: '"Cascadia Code", "JetBrains Mono", "Fira Code", Consolas, monospace',
      size: 14,
      lineHeight: 1.2,
    },
    opacity: 1,
  },
  {
    id: 'catppuccin-macchiato',
    name: 'Catppuccin Macchiato',
    isBuiltIn: true,
    colors: {
      background: '#24273a',
      foreground: '#cad3f5',
      cursor: '#f4dbd6',
      selection: '#494d64',
      black: '#494d64',
      red: '#ed8796',
      green: '#a6da95',
      yellow: '#eed49f',
      blue: '#8aadf4',
      magenta: '#f5bde6',
      cyan: '#8bd5ca',
      white: '#b8c0e0',
      brightBlack: '#5b6078',
      brightRed: '#ed8796',
      brightGreen: '#a6da95',
      brightYellow: '#eed49f',
      brightBlue: '#8aadf4',
      brightMagenta: '#f5bde6',
      brightCyan: '#8bd5ca',
      brightWhite: '#a5adcb',
    },
    font: {
      family: '"Cascadia Code", "JetBrains Mono", "Fira Code", Consolas, monospace',
      size: 14,
      lineHeight: 1.2,
    },
    opacity: 1,
  },
];

export const DEFAULT_LAYOUT_PRESETS: LayoutPreset[] = [
  {
    id: 'single',
    name: 'Single',
    description: 'One terminal taking the full space',
    layout: null,
    icon: '□',
  },
  {
    id: 'split-horizontal',
    name: 'Split Horizontal',
    description: 'Two terminals side by side',
    layout: {
      direction: 'row',
      first: 'terminal-1',
      second: 'terminal-2',
      splitPercentage: 50,
    },
    icon: '▥',
  },
  {
    id: 'split-vertical',
    name: 'Split Vertical',
    description: 'Two terminals stacked',
    layout: {
      direction: 'column',
      first: 'terminal-1',
      second: 'terminal-2',
      splitPercentage: 50,
    },
    icon: '▤',
  },
  {
    id: 'quad',
    name: 'Quad',
    description: 'Four terminals in a grid',
    layout: {
      direction: 'row',
      first: {
        direction: 'column',
        first: 'terminal-1',
        second: 'terminal-2',
        splitPercentage: 50,
      },
      second: {
        direction: 'column',
        first: 'terminal-3',
        second: 'terminal-4',
        splitPercentage: 50,
      },
      splitPercentage: 50,
    },
    icon: '▦',
  },
];

export const IPC_CHANNELS = {
  TERMINAL: {
    CREATE: 'terminal:create',
    CREATED: 'terminal:created',
    WRITE: 'terminal:write',
    RESIZE: 'terminal:resize',
    KILL: 'terminal:kill',
    GET_ALL: 'terminal:getAll',
    GET: 'terminal:get',
    OUTPUT: 'terminal:output',
    EXIT: 'terminal:exit',
    TITLE: 'terminal:title',
  },
  CONFIG: {
    GET: 'config:get',
    SET: 'config:set',
    DELETE: 'config:delete',
    GET_WORKSPACE: 'config:getWorkspace',
    SAVE_WORKSPACE: 'config:saveWorkspace',
  },
  AGENT: {
    GET_ALL: 'agent:getAll',
    ADD: 'agent:add',
    REMOVE: 'agent:remove',
    UPDATE: 'agent:update',
    GET_RECENT_DIRECTORIES: 'agent:getRecentDirectories',
    ADD_RECENT_DIRECTORY: 'agent:addRecentDirectory',
    REMOVE_RECENT_DIRECTORY: 'agent:removeRecentDirectory',
    CLEAR_RECENT_DIRECTORIES: 'agent:clearRecentDirectories',
    SELECT_DIRECTORY: 'agent:selectDirectory',
  },
  APP: {
    GET_SHELLS: 'app:getShells',
    MINIMIZE: 'app:minimize',
    MAXIMIZE: 'app:maximize',
    CLOSE: 'app:close',
    IS_MAXIMIZED: 'app:isMaximized',
    MAXIMIZED: 'app:maximized',
  },
  THEME: {
    EXPORT: 'theme:export',
    IMPORT: 'theme:import',
  },
} as const;
