import type { AgentPreset } from './types/agent';
import type { ThemeConfig } from './types/theme';
import type { ShellInfo, ShellType } from './types/terminal';
import type { LayoutPreset } from './types/layout';

export const APP_NAME = 'Agenteck';
export const APP_VERSION = '1.0.0';

// Safe check for process.platform (not available in renderer)
export const DEFAULT_SHELL: ShellType =
  typeof process !== 'undefined' && process.platform === 'win32' ? 'powershell' : 'bash';

export const SHELL_CONFIGS: Record<string, Partial<ShellInfo>> = {
  powershell: {
    id: 'powershell',
    name: 'PowerShell',
    path: 'powershell.exe',
    args: ['-NoLogo'],
  },
  cmd: {
    id: 'cmd',
    name: 'Command Prompt',
    path: 'cmd.exe',
  },
  bash: {
    id: 'bash',
    name: 'Bash',
    path: '/bin/bash',
    args: ['--login'],
  },
  zsh: {
    id: 'zsh',
    name: 'Zsh',
    path: '/bin/zsh',
    args: ['--login'],
  },
  wsl: {
    id: 'wsl',
    name: 'WSL',
    path: 'wsl.exe',
  },
};

// Available agent presets that users can add to their workspace
export const AVAILABLE_AGENTS: AgentPreset[] = [
  {
    id: 'claude-code',
    name: 'Claude Code',
    command: 'claude',
    args: [],
    description: 'Anthropic\'s CLI for Claude AI assistance',
    website: 'https://claude.ai/claude-code',
    isBuiltIn: true,
  },
  {
    id: 'copilot-cli',
    name: 'GitHub Copilot CLI',
    command: 'gh',
    args: ['copilot'],
    description: 'GitHub Copilot in the command line',
    website: 'https://githubnext.com/projects/copilot-cli',
    isBuiltIn: true,
  },
  {
    id: 'aider',
    name: 'Aider',
    command: 'aider',
    args: [],
    description: 'AI pair programming in your terminal',
    website: 'https://aider.chat',
    isBuiltIn: true,
  },
  {
    id: 'cline',
    name: 'Cline',
    command: 'cline',
    args: [],
    description: 'Autonomous coding agent',
    website: 'https://github.com/cline/cline',
    isBuiltIn: true,
  },
  {
    id: 'continue',
    name: 'Continue',
    command: 'continue',
    args: [],
    description: 'Open-source AI code assistant',
    website: 'https://continue.dev',
    isBuiltIn: true,
  },
];

export const DEFAULT_TERMINAL_THEME: ThemeConfig = {
  id: 'default-dark',
  name: 'Default Dark',
  isBuiltIn: true,
  colors: {
    background: '#1e1e2e',
    foreground: '#cdd6f4',
    cursor: '#f5e0dc',
    cursorAccent: '#1e1e2e',
    selection: '#45475a',
    selectionForeground: '#cdd6f4',
    black: '#45475a',
    red: '#f38ba8',
    green: '#a6e3a1',
    yellow: '#f9e2af',
    blue: '#89b4fa',
    magenta: '#f5c2e7',
    cyan: '#94e2d5',
    white: '#bac2de',
    brightBlack: '#585b70',
    brightRed: '#f38ba8',
    brightGreen: '#a6e3a1',
    brightYellow: '#f9e2af',
    brightBlue: '#89b4fa',
    brightMagenta: '#f5c2e7',
    brightCyan: '#94e2d5',
    brightWhite: '#a6adc8',
  },
  font: {
    family: '"Cascadia Code", "JetBrains Mono", "Fira Code", Consolas, monospace',
    size: 14,
    lineHeight: 1.2,
  },
  opacity: 1,
};

export const BUILT_IN_THEMES: ThemeConfig[] = [
  DEFAULT_TERMINAL_THEME,
  {
    id: 'dracula',
    name: 'Dracula',
    isBuiltIn: true,
    colors: {
      background: '#282a36',
      foreground: '#f8f8f2',
      cursor: '#f8f8f2',
      selection: '#44475a',
      black: '#21222c',
      red: '#ff5555',
      green: '#50fa7b',
      yellow: '#f1fa8c',
      blue: '#bd93f9',
      magenta: '#ff79c6',
      cyan: '#8be9fd',
      white: '#f8f8f2',
      brightBlack: '#6272a4',
      brightRed: '#ff6e6e',
      brightGreen: '#69ff94',
      brightYellow: '#ffffa5',
      brightBlue: '#d6acff',
      brightMagenta: '#ff92df',
      brightCyan: '#a4ffff',
      brightWhite: '#ffffff',
    },
    font: {
      family: '"Cascadia Code", "JetBrains Mono", "Fira Code", Consolas, monospace',
      size: 14,
      lineHeight: 1.2,
    },
    opacity: 1,
  },
  {
    id: 'nord',
    name: 'Nord',
    isBuiltIn: true,
    colors: {
      background: '#2e3440',
      foreground: '#d8dee9',
      cursor: '#d8dee9',
      selection: '#434c5e',
      black: '#3b4252',
      red: '#bf616a',
      green: '#a3be8c',
      yellow: '#ebcb8b',
      blue: '#81a1c1',
      magenta: '#b48ead',
      cyan: '#88c0d0',
      white: '#e5e9f0',
      brightBlack: '#4c566a',
      brightRed: '#bf616a',
      brightGreen: '#a3be8c',
      brightYellow: '#ebcb8b',
      brightBlue: '#81a1c1',
      brightMagenta: '#b48ead',
      brightCyan: '#8fbcbb',
      brightWhite: '#eceff4',
    },
    font: {
      family: '"Cascadia Code", "JetBrains Mono", "Fira Code", Consolas, monospace',
      size: 14,
      lineHeight: 1.2,
    },
    opacity: 1,
  },
  {
    id: 'monokai',
    name: 'Monokai',
    isBuiltIn: true,
    colors: {
      background: '#272822',
      foreground: '#f8f8f2',
      cursor: '#f8f8f2',
      selection: '#49483e',
      black: '#272822',
      red: '#f92672',
      green: '#a6e22e',
      yellow: '#f4bf75',
      blue: '#66d9ef',
      magenta: '#ae81ff',
      cyan: '#a1efe4',
      white: '#f8f8f2',
      brightBlack: '#75715e',
      brightRed: '#f92672',
      brightGreen: '#a6e22e',
      brightYellow: '#f4bf75',
      brightBlue: '#66d9ef',
      brightMagenta: '#ae81ff',
      brightCyan: '#a1efe4',
      brightWhite: '#f9f8f5',
    },
    font: {
      family: '"Cascadia Code", "JetBrains Mono", "Fira Code", Consolas, monospace',
      size: 14,
      lineHeight: 1.2,
    },
    opacity: 1,
  },
  {
    id: 'tokyo-night',
    name: 'Tokyo Night',
    isBuiltIn: true,
    colors: {
      background: '#1a1b26',
      foreground: '#c0caf5',
      cursor: '#c0caf5',
      selection: '#33467c',
      black: '#15161e',
      red: '#f7768e',
      green: '#9ece6a',
      yellow: '#e0af68',
      blue: '#7aa2f7',
      magenta: '#bb9af7',
      cyan: '#7dcfff',
      white: '#a9b1d6',
      brightBlack: '#414868',
      brightRed: '#f7768e',
      brightGreen: '#9ece6a',
      brightYellow: '#e0af68',
      brightBlue: '#7aa2f7',
      brightMagenta: '#bb9af7',
      brightCyan: '#7dcfff',
      brightWhite: '#c0caf5',
    },
    font: {
      family: '"Cascadia Code", "JetBrains Mono", "Fira Code", Consolas, monospace',
      size: 14,
      lineHeight: 1.2,
    },
    opacity: 1,
  },
];

export const DEFAULT_LAYOUT_PRESETS: LayoutPreset[] = [
  {
    id: 'single',
    name: 'Single',
    description: 'One terminal taking the full space',
    layout: null,
    icon: '□',
  },
  {
    id: 'split-horizontal',
    name: 'Split Horizontal',
    description: 'Two terminals side by side',
    layout: {
      direction: 'row',
      first: 'terminal-1',
      second: 'terminal-2',
      splitPercentage: 50,
    },
    icon: '▥',
  },
  {
    id: 'split-vertical',
    name: 'Split Vertical',
    description: 'Two terminals stacked',
    layout: {
      direction: 'column',
      first: 'terminal-1',
      second: 'terminal-2',
      splitPercentage: 50,
    },
    icon: '▤',
  },
  {
    id: 'quad',
    name: 'Quad',
    description: 'Four terminals in a grid',
    layout: {
      direction: 'row',
      first: {
        direction: 'column',
        first: 'terminal-1',
        second: 'terminal-2',
        splitPercentage: 50,
      },
      second: {
        direction: 'column',
        first: 'terminal-3',
        second: 'terminal-4',
        splitPercentage: 50,
      },
      splitPercentage: 50,
    },
    icon: '▦',
  },
];

export const IPC_CHANNELS = {
  TERMINAL: {
    CREATE: 'terminal:create',
    WRITE: 'terminal:write',
    RESIZE: 'terminal:resize',
    KILL: 'terminal:kill',
    GET_ALL: 'terminal:getAll',
    GET: 'terminal:get',
    OUTPUT: 'terminal:output',
    EXIT: 'terminal:exit',
    TITLE: 'terminal:title',
  },
  CONFIG: {
    GET: 'config:get',
    SET: 'config:set',
    DELETE: 'config:delete',
    GET_WORKSPACE: 'config:getWorkspace',
    SAVE_WORKSPACE: 'config:saveWorkspace',
  },
  AGENT: {
    GET_RECENT_DIRECTORIES: 'agent:getRecentDirectories',
    ADD_RECENT_DIRECTORY: 'agent:addRecentDirectory',
    REMOVE_RECENT_DIRECTORY: 'agent:removeRecentDirectory',
    CLEAR_RECENT_DIRECTORIES: 'agent:clearRecentDirectories',
    SELECT_DIRECTORY: 'agent:selectDirectory',
  },
  APP: {
    GET_SHELLS: 'app:getShells',
    MINIMIZE: 'app:minimize',
    MAXIMIZE: 'app:maximize',
    CLOSE: 'app:close',
    IS_MAXIMIZED: 'app:isMaximized',
    MAXIMIZED: 'app:maximized',
  },
} as const;
